### PR TITLE
[DO NOT MERGE] Added rake task for CV capsule sync metrics

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by sthirugn** [comment]
@mccun934  any thoughts on this?

**Comment by mccun934** [comment]
actually, why don't we just submit this as a PR to Katello itself. no need to keep this in satellite-support

**Comment by mccun934** [comment]
If it stalls there, we can merge it here, but I'd rather see this just be part of katello proper

**Comment by sthirugn** [comment]
I will move this PR to katello proper and then close this.

**Comment by sthirugn** [comment]
Many tuning related changed went in after this.  I am going to close this PR now and work on katello *only* if there is a demand for this kind of a tool.

**Pull request closed without merging**
